/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.model.user.User;
import javax.swing.JSplitPane;

/**
 *
 * @author Zhen Luo <luo.zhe@northeastern.edu>
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {
    
    private JSplitPane splitPanel;
    
    private User user;
    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    public SystemAdminWorkAreaJPanel(JSplitPane splitPanel, User user) {
        initComponents();
        this.splitPanel = splitPanel;
        this.user = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnMedical = new javax.swing.JButton();
        btnTax = new javax.swing.JButton();
        btnUtility = new javax.swing.JButton();
        lblWelcom = new javax.swing.JLabel();
        lblValue = new javax.swing.JLabel();
        btnPublicService = new javax.swing.JButton();
        btnCustomer = new javax.swing.JButton();
        btnManageBill = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setText("My Work Area -Adminstrative");

        btnMedical.setText("Manage Medical Organization");
        btnMedical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicalActionPerformed(evt);
            }
        });

        btnTax.setText("Manage Tax Organization");
        btnTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaxActionPerformed(evt);
            }
        });

        btnUtility.setText("Manage Utility Organization");
        btnUtility.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUtilityActionPerformed(evt);
            }
        });

        lblWelcom.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblWelcom.setText("Welcome! Admin");

        btnPublicService.setText("Manage Public Service Organization");
        btnPublicService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPublicServiceActionPerformed(evt);
            }
        });

        btnCustomer.setText("Manage Customer");
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });

        btnManageBill.setText("Manage Bills");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btnUtility))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMedical, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTax, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPublicService, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManageBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(lblWelcom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblValue, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(197, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCustomer, btnMedical, btnPublicService, btnTax, btnUtility});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(lblTitle)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWelcom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValue))
                .addGap(18, 18, 18)
                .addComponent(btnUtility)
                .addGap(18, 18, 18)
                .addComponent(btnTax)
                .addGap(18, 18, 18)
                .addComponent(btnMedical)
                .addGap(18, 18, 18)
                .addComponent(btnPublicService)
                .addGap(18, 18, 18)
                .addComponent(btnCustomer)
                .addGap(18, 18, 18)
                .addComponent(btnManageBill)
                .addContainerGap(214, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMedicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicalActionPerformed
//        // TODO add your handling code here:
       SystemAdminManageOrganizationJPanel sj = new SystemAdminManageOrganizationJPanel("Medical");
                splitPanel.setRightComponent(sj);
//        ManageUserAccountJPanel muajp = new ManageUserAccountJPanel(userProcessContainer, enterprise);
//        userProcessContainer.add("ManageUserAccountJPanel", muajp);
//
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMedicalActionPerformed

    private void btnTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaxActionPerformed
         SystemAdminManageOrganizationJPanel sj = new SystemAdminManageOrganizationJPanel("Tax");
                splitPanel.setRightComponent(sj);
//        ManageEmployeeJPanel manageEmployeeJPanel = new ManageEmployeeJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
//        userProcessContainer.add("manageEmployeeJPanel", manageEmployeeJPanel);
//
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnTaxActionPerformed

    private void btnUtilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUtilityActionPerformed
                SystemAdminManageOrganizationJPanel sj = new SystemAdminManageOrganizationJPanel("Utility");
                splitPanel.setRightComponent(sj);
                
//        ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
//        userProcessContainer.add("manageOrganizationJPanel", manageOrganizationJPanel);
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnUtilityActionPerformed

    private void btnPublicServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPublicServiceActionPerformed
        // TODO add your handling code here:
                SystemAdminManageOrganizationJPanel sj = new SystemAdminManageOrganizationJPanel("Public");
                splitPanel.setRightComponent(sj);
    }//GEN-LAST:event_btnPublicServiceActionPerformed

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCustomerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnManageBill;
    private javax.swing.JButton btnMedical;
    private javax.swing.JButton btnPublicService;
    private javax.swing.JButton btnTax;
    private javax.swing.JButton btnUtility;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblValue;
    private javax.swing.JLabel lblWelcom;
    // End of variables declaration//GEN-END:variables
}
