/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.SystemAdminWorkArea;

import Business.model.order.Order;
import Business.model.user.User;
import Business.service.UserService;
import java.util.List;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;
import static userinterface.MainJFrame.infoBox;

/**
 *
 * @author Frank
 */
public class SystemAdminManageOrganizationJPanel extends javax.swing.JPanel {
    String type;
    UserService us;
    
    private JSplitPane splitPanel;
    
    private User user;
    /**
     * Creates new form SystemAdminManageMedical
     */
    public SystemAdminManageOrganizationJPanel(JSplitPane splitPanel, User user,String type) {
        initComponents();
        this.type = type;
        this.us = new UserService();
        this.splitPanel = splitPanel;
        this.user = user;
        preWork();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnChange = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();

        btnChange.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnChange.setText("Change");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });

        btnNew.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNew.setText("New");

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblUser.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "UserName", "Type", "Role", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblUser);

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitle.setText("Medical,public,tax,util/customer");

        btnDelete.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnChange)
                                    .addGap(332, 332, 332)
                                    .addComponent(btnDelete))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblTitle)
                                    .addGap(260, 260, 260))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnBack)
                .addGap(40, 40, 40)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnChange))
                .addGap(18, 18, 18)
                .addComponent(btnNew)
                .addContainerGap(110, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
         int selectedRow = tblUser.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        String name = (String)tblUser.getValueAt(selectedRow, 0);
        
      
         if( us.deletedByName(name)>0){
              infoBox("deleted user success!!", "Valid");
        }else{
              infoBox("deleted user fail!!", "invalid");
        }
         
         populateTable(us.getListByType(type));
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        SystemAdminWorkAreaJPanel sa = new SystemAdminWorkAreaJPanel(splitPanel,user);
        splitPanel.setRightComponent(sa);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblUser.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        User user = new User();
        user.setUsername((String)tblUser.getValueAt(selectedRow, 0)); 
        user.setType((String)tblUser.getValueAt(selectedRow, 1)); 
        user.setRole((String)tblUser.getValueAt(selectedRow, 2));
        user.setPassword((String)tblUser.getValueAt(selectedRow, 3));
        
        if( us.modifyUserByName(user)>0){
              infoBox("Modify user success!!", "Valid");
        }else{
             infoBox("Modify user fail!!", "invalid");
        }
       
        populateTable(us.getListByType(type));
    }//GEN-LAST:event_btnChangeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblUser;
    // End of variables declaration//GEN-END:variables

    private void preWork() {
        
       lblTitle.setText(this.type);
       populateTable(us.getListByType(this.type));
       
    }
     public void populateTable(List<User> users){
        
          DefaultTableModel userModel = (DefaultTableModel) tblUser.getModel();
     
          userModel.setRowCount(0);

          for(User user:users){
            Object[] row = new Object[4];
            row[0] = user.getUsername();
            row[1] = user.getType();
            row[2] = user.getRole();
            row[3] = user.getPassword();

            userModel.addRow(row);
         }
    }
}
