/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;


import Business.model.order.Order;
import Business.model.order.PayMethod;
import Business.model.user.User;
import Business.service.CustomerService;
import Business.service.OrderService;
import Business.service.PayService;
import Business.service.UserService;
import java.awt.CardLayout;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;
import static userinterface.MainJFrame.infoBox;


/**
 *
 * @author raunak
 */
public class CustomerPayBillJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private JSplitPane splitPanel;
    private User user;
    private CustomerService cs;
    private OrderService os;
    private UserService us; 
    private PayService ps;
    private String method;
    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public CustomerPayBillJPanel(JSplitPane splitPanel, User user,String orderId) {
        initComponents();
        
     
        this.splitPanel = splitPanel;
        this.user = user;
        this.cs = new CustomerService();
        this.os = new OrderService();
        this.us = new UserService();
        this.ps = new PayService();

        preWork(orderId);
        
        cbxSelectPayment.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                 cbxSelectCard.removeAllItems();
                 if (e.getStateChange() == ItemEvent.SELECTED) {
                     method = (String)e.getItem();  
                     
                    List<PayMethod> list =  ps.getNumberByMethod(method,user.getUsername());
                    for(PayMethod pay:list){
                            cbxSelectCard.addItem(pay.getCardNumber());
                    }
                 }           
            }   
       });  
       
    }
    
    void preWork(String id){
         List<PayMethod> list =  ps.getListByUser(user.getUsername());
         Set<String> set = new HashSet<>();
         for(PayMethod pay:list){
             String method = pay.getMethod();
             if(set.add(method)){
                 cbxSelectPayment.addItem(method);
             } 
         }
         
         populateInformation(os.getOrderById(id));
          
    }
     private void populateInformation(Order order) {
      // setEditable(false)
        SimpleDateFormat sdf = new SimpleDateFormat( "MM/dd/yyyy" ); 
        txtDepartment.setText(us.getTypeByName(order.getCompanyId()));
        txtFrom.setText(order.getCompanyId());
        txtTotalAmount.setText(order.getFee()+"");
        txtPaymentDue.setText(sdf.format(order.getDdl()));
        txtBillNumber.setText(order.getId()+"");
        
    } 

    
   

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        enterpriseLabel1 = new javax.swing.JLabel();
        lblDepartment = new javax.swing.JLabel();
        lblFrom = new javax.swing.JLabel();
        lblTotalAmount = new javax.swing.JLabel();
        lblPaymentDue = new javax.swing.JLabel();
        lblSelectPayment = new javax.swing.JLabel();
        cbxSelectPayment = new javax.swing.JComboBox<>();
        lblBillNumber = new javax.swing.JLabel();
        btnPayment = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        cbxSelectCard = new javax.swing.JComboBox<>();
        txtDepartment = new javax.swing.JLabel();
        txtFrom = new javax.swing.JLabel();
        txtTotalAmount = new javax.swing.JLabel();
        txtPaymentDue = new javax.swing.JLabel();
        txtBillNumber = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextField1.setText("jTextField1");

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        enterpriseLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel1.setText("Pay your Bill:");

        lblDepartment.setText("Department:");

        lblFrom.setText("From:");

        lblTotalAmount.setText("Total Amount:");

        lblPaymentDue.setText("Payment due:");

        lblSelectPayment.setText("Select a payment method:");

        cbxSelectPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Payment" }));

        lblBillNumber.setText("Bill Number:");

        btnPayment.setText("Make Payment");
        btnPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        cbxSelectCard.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Card Number" }));

        txtDepartment.setText("txt");

        txtFrom.setText("txt");

        txtTotalAmount.setText("txt");

        txtPaymentDue.setText("txt");

        txtBillNumber.setText("txt");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblBillNumber)
                            .addComponent(lblPaymentDue)
                            .addComponent(lblTotalAmount)
                            .addComponent(lblFrom)
                            .addComponent(lblDepartment)
                            .addComponent(enterpriseLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPaymentDue)
                            .addComponent(txtFrom)
                            .addComponent(txtDepartment)
                            .addComponent(txtTotalAmount)
                            .addComponent(txtBillNumber))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSelectPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxSelectPayment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxSelectCard, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)))
                .addContainerGap(247, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterpriseLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDepartment)
                            .addComponent(txtDepartment))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFrom)
                            .addComponent(txtFrom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalAmount)
                            .addComponent(txtTotalAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPaymentDue)
                            .addComponent(txtPaymentDue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSelectPayment)
                        .addGap(18, 18, 18)
                        .addComponent(cbxSelectPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbxSelectCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBillNumber)
                    .addComponent(txtBillNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPayment))
                .addGap(159, 159, 159))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentActionPerformed
        // TODO add your handling code here:
        String id = txtBillNumber.getText();
        if(os.finishPay(id)>0){
           infoBox("Payment finished!!", "Valid");
        }else{
           infoBox("Payment fail!!", "invalid");
        }
    }//GEN-LAST:event_btnPaymentActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CustomerWorkAreaJPanel cp = new CustomerWorkAreaJPanel(splitPanel,user);
        splitPanel.setRightComponent(cp);
    }//GEN-LAST:event_btnBackActionPerformed
// public void populateTable(List<Restaurant> list){
//         
//        DefaultTableModel priceModel = (DefaultTableModel) PriceTable.getModel();
//     
//        priceModel.setRowCount(0);
//           
//         for(Restaurant rest:list){
//            Object[] row = new Object[4];
//            
//            List<Food> menu =  rest.getMenu();
//              
//            row[0] = rest.getName();
//            row[1] = menu.get(0).getPrice();
//            row[2] = menu.get(1).getPrice();
//            
//            try{
//                if(menu.get(2)!=null) row[3] = menu.get(2).getPrice();
//            }catch(Exception e){
//                    System.out.print("长度未到");
//            }
//            
//            priceModel.addRow(row);
//         }
//  
//    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPayment;
    private javax.swing.JComboBox<String> cbxSelectCard;
    private javax.swing.JComboBox<String> cbxSelectPayment;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblBillNumber;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblPaymentDue;
    private javax.swing.JLabel lblSelectPayment;
    private javax.swing.JLabel lblTotalAmount;
    private javax.swing.JLabel txtBillNumber;
    private javax.swing.JLabel txtDepartment;
    private javax.swing.JLabel txtFrom;
    private javax.swing.JLabel txtPaymentDue;
    private javax.swing.JLabel txtTotalAmount;
    // End of variables declaration//GEN-END:variables

   

    
}
